### ISSUE TITLE
想问一下你的转移概率矩阵是怎么构造的？

### ISSUE THREAD

**Issue by tangbotony** [hit-computer/MH#1]
想问一下你的转移概率矩阵是怎么构造的？你文章和代码里面没有提这个问题。

**Comment by hit-computer** [comment]
文章中其实是有的，公式中的Q(i,j)就是转移概率矩阵（由alpha(i,j)和q(i,j)共同构成），不过由于alpha(i,j)是通过q(i,j)来计算的，所以只需要构造q(i,j)即可。而q(i,j)可以是任意一个矩阵就行（只是这个矩阵的每一行是一个概率分布，即满足每一行相加等于1）。所以在“几点说明与建议”中又有提到q(i,j)可以直接等于一个概率分布p(i)，这相当于无论j取什么q(i,j)=p(i)。也可参见代码中的34行到36行。谢谢啦
